### ISSUE TITLE
添加router路由守卫中间件时(验证是否登录)时 pinia还未创建 所以引发报错

### ISSUE THREAD

**Issue by stywell** [zhazhazhu/pinia-oidc#5]
我在@/router/index.js 下 引入
import { piniaOidcCreateRouterMiddleware } from 'pinia-oidc'
import { useOidcStore } from '@/stores/oidc.js'
const router = createRouter(...)
router.beforeEach(piniaOidcCreateRouterMiddleware(useOidcStore())) // 这时执行useOidcStore方法  Pinia还未被安装

控制台报错:
Uncaught Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Did you forget to install pinia?
	const pinia = createPinia()
	app.use(pinia)

官方的解释:
https://pinia.vuejs.org/zh/core-concepts/outside-component-usage.html

我本地 把那vue/nuxt中间件方法的参数 改为了 Function  然后 进去之后执行之后在判断~
因为不太熟悉TS类型  所以就不提交PR了 在丢人~
![image](https://github.com/zhazhazhu/pinia-oidc/assets/19585647/31cd039b-69e0-4379-b3f1-d652740f2183)
![image](https://github.com/zhazhazhu/pinia-oidc/assets/19585647/47694c20-f771-4d82-8101-bb7d963fc69f)

是我用法错误码?
这个路由守卫 在什么时机加呢?

**Comment by zhazhazhu** [comment]
添加中间件的时候，确保你的router,pinia都已经初始化。最好有你的复现链接

**Comment by zhazhazhu** [comment]
如果你使用了最新的vue3，推荐使用[vue3-oidc](https://github.com/zhazhazhu/vue3-oidc)，他不需要借助任何store,router

**Comment by stywell** [comment]
> 如果你使用了最新的vue3，推荐使用[vue3-oidc](https://github.com/zhazhazhu/vue3-oidc)，他不需要借助任何store,router

谢谢 为了从vue2 相对来说平滑升级到vue3 所以才选择了老的模式~
router添加中间件的时候  这个时候pinia确实没有初始化  所以把方法传进去 暂时先解决了~  后期我研究一下 vue3-oidc
